name: devops app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: List Files
      run: |
        echo "List files in the repository"
        ls -a

    - name: Install dependencies
      run: |
        echo "Install dependencies"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint Test
      run: |
        echo "Lint Test"
        python -m pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=69 --statistics
    
    - name: Test
      run: |
        echo "Test"
        python -m pytest
